### PR TITLE
Update syntax for Terraform v0.12

### PR DESCRIPTION
**Pull request by asciigirl**
Updates syntax for terraform v0.12.

Includes changes proposed on CloudHealth/terraform-cloudhealth-iam/pull/29 + pending fixes on outputs.tf file. 

Resolves CloudHealth/terraform-cloudhealth-iam/issues/25

### CODE REVIEW

**Review by bateller — DISMISSED** [review]

**Comment by angelconcepcion** [comment]
Hi, do you know if this is backward compatible with previous versions of Terraform or will this force other users to update their Terraform version or use a previous version of this module?

**Comment by bateller** [comment]
> Hi, do you know if this is backward compatible with previous versions of Terraform or will this force other users to update their Terraform version or use a previous version of this module?

@angelconcepcion This PR would not be backwards compatible with Terraform v0.11, but should be compatible with Terraform version >= v0.12

Terraform v0.12 has more strict syntax restrictions like requiring argument syntax for arguments and nested block syntax for nested blocks. Also regarding variables, previously Terraform required using seemingly-redundant list brackets around a single expression. This too has changed.

More information can be found here: https://www.terraform.io/upgrade-guides/0-12.html

I'm not sure there is a way around making a backwards and forward compatible version.

My recommendation would be to create a new release candidate that expressly states its not backwards compatible with Terraform v0.11 or older.

Then possibly an addendum in the README stating release version `v0.1.0` (or whatever version you decide to tag) is supported only by Terraform v0.12 and newer

**Comment by asciigirl** [comment]
Hey Angel,

No, this breaks compatibility with Terraform 0.11. I think the best
approach in this case would be to make a new release and add in the
changelog/README which version works with Terraform 0.11 and which one with
Terraform 0.12. I can send you the PR with the fix in the README. I would
suggest making v0.1.0 for Terraform 0.12 and v0.0.18 for Terraform 0.11.
Let me know what you think and I will update my PR.

Thanks for working on this module! It's very useful for my team.
m*

**Comment by nikolaifa** [comment]
Hey,
Is there any ETA on when this will be merged? We are using the module in our project and are looking into upgrading to terraform version 0.13

**Comment by fishfacemcgee** [comment]
@angelconcepcion is breaking TF0.11 support a non-starter for CloudHealth? It seems like the release tagging would let people freeze to/roll back to (if they're not currently targeting a tag) a TF 0.11 compatible version while they work on upgrading.

**Comment by angelconcepcion** [comment]
Sorry for the wait guys! Will be merging this now and making the changes in the README.

**Comment by angelconcepcion** [comment]
@asciigirl I think your idea is great! I'd welcome the fix in README. My worry was forcing users to have to freeze a tag and/or not knowing how many users still use TF 0.11.

**Comment by asciigirl** [comment]
@angelconcepcion Great! I will get the README fixed right away ;-)

**Review by bateller — APPROVED** [review]

**Comment by asciigirl** [comment]
@angelconcepcion Updated the README.

**Review by angelconcepcion — APPROVED** [review]

**Pull request merged**
